const { searchStory } = require("../controllers/reader.js");
const { getStory } = require("../controllers/reader.js");
const { rateStory } = require("../controllers/reader.js");
const { getTopStoriesRating } = require("../controllers/reader.js");
const { appendToFavourite } = require("../controllers/reader.js");
const { getFavouriteStories } = require("../controllers/reader.js");
const { getScene } = require("../controllers/reader.js");
const { folowers } = require("../controllers/reader.js");
const { getMyStory } = require("../controllers/reader.js");
const {getstoryAll}=require("../controllers/reader.js");
const express = require("express");
const router = express.Router();
const authMiddleware = require("../middleware/authmiddleware.js");
router.get("/searchStory", authMiddleware, searchStory);
router.get("/getStory/:idStory", authMiddleware, getStory);
router.post("/rateStory/:idStory", authMiddleware, rateStory);
router.get("/getTopStories", authMiddleware, getTopStoriesRating);
router.post("/appendToFavourite/:idStory", authMiddleware, appendToFavourite);
router.get("/getFavouriteStories", authMiddleware, getFavouriteStories);
router.get("/getScene/:idScene", authMiddleware, getScene);
router.post("/follow/:idWriter", authMiddleware, folowers);
router.post("/getMyStory", authMiddleware, getMyStory);
router.get("/getstoryAll/:idstory", authMiddleware, getstoryAll);
module.exports = router;
